version: '3'
services:
  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    # image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    # image: bossjones/elasticsearch:v5.6.2
    build: ./build/docker-elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"
      MINIMUM_MASTER_NODES: "1"
      XPACK_MONITORING_ENABLED: "false"
      XPACK_SECURITY_ENABLED: "false"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data:/data

  fluentd:
    build: ./build/fluentd-elasticsearch
    # image: bossjones/fluentd-elasticsearch:v2.5.0
    volumes:
      # - ./fluentd/conf:/etc/fluentd
      - ./fluentd/conf:/fluentd/etc
      - ./log:/log
      - ./grok.d:/grok.d
    environment:
      FLUENTD_ARGS: "--no-supervisor -vv"
      TZ: "UTC"
      TAIL_BUF_LIMIT: "5MB"
      FLUENT_CONF: "/fluentd/etc/fluent.conf"
    ports:
      - 8080:8080
      - 24231:24231
      - 24220:24220

  kibana:
    # image: docker.elastic.co/kibana/kibana:6.2.4
    # image: docker.elastic.co/kibana/kibana:5.6.2
    # image: bossjones/kibana:5.6.2
    build: ./build/docker-kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_MONITORING_ENABLED: "false"
      XPACK_SECURITY_ENABLED: "false"
    ports:
      - 5601:5601
    volumes:
      - ./data:/data
